### PR TITLE
Walk/pretty print comments

### PR DESCRIPTION
**Pull request by aslakhellesoy**
## Summary

* Walk comments in `walkGherkinDocument`
* Pretty print comments in `pretty`

## Details

Keep a stack of comments and pop/walk comments until the current AST node.

## How Has This Been Tested?

I've just added a couple of unit tests - we need more thorough tests for this:

* [ ] Add comments everywhere in `walkGherkinDocumentTest`
* [ ] Add more edge case tests for `pretty`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [x] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
@nddipiazza @jamietanna I'd welcome your feedback/review on this.

**Review by jamietanna — CHANGES_REQUESTED** [review]
Unfortunately this still doesn't quite work. I.e. [`datatables_with_comment.feature`](https://gitlab.com/jamietanna/gherkin-formatter/-/blob/20bd92017300edeefa0bb23a52f529ed66d8f054/src/test/resources/output/datatables_with_comment.feature) loses the comments, and [`trailing_scenario_comments`](https://gitlab.com/jamietanna/gherkin-formatter/-/blob/6aa1e17d01b2094bc13c6c6d8e5284f8179707e1/src/test/resources/output/trailing_scenario_comments.feature) puts all the comments at the top of the file

**Comment by aslakhellesoy** [comment]
Yes, I'm aware it's still incomplete and buggy. But what do you think of the general approach of using a stack that we pop as we traverse?

**Comment by nddipiazza** [comment]
Looks like the right idea. Sounds like just a matter of gathering a ton of feature files, running, and fixing what needs fixed.

**Comment by aslakhellesoy** [comment]
Testing with a ton of files is useful, but I think we can get pretty good confidence/coverage by modifying this test:

https://github.com/cucumber/common/blob/main/gherkin-utils/javascript/test/walkGherkinDocumentTest.ts

I'd suggest adding comments like

```
# 1
```
```
# 2
```
```
# 3
```
etc around the file and modify the expected result at the end. That way we know we're traversing correctly (which is the basis for correct pretty formatting).

**Comment by jamietanna** [comment]
Using a stack that pops makes sense - that's how I've been doing it with my Java library, the difficulty right now is trying to make sure it pops in the right place :sweat_smile:

**Comment by badeball** [comment]
I took a stab at this. I had one more contraint though, namely whitespace retention. One thing I like about other "prettifiers" is the ability to truncate duplicate whitespace, but otherwise retain it. With that I mean that both the following gherkin documents would be "valid" and "prettified" to itself:

```feature
Feature: foo
  Scenario: bar
    Given some step
```

```feature
Feature: foo

  Scenario: bar
    Given some step
```

I was looking at the AST in connection with this. There's two things so far I've noticed missing, that I need in order to get perfect prettifying as described above.

- Location of the dialect commet, EG. `# language: no` (it's not added to ast's `comments` section)
- Location attribute of description blocks (they only exists as string of EG. scenarios)

Would you be open to extending messages to include location in descriptions, as well as appending dialect-comments to comments?

Aside from these things, I was able to prettify _and_ retain whitespace and truncate duplicate. I did however not use `walkGherkinDocument` :scream_cat: . My implementation can be seen below.

```ts
import { AstBuilder, Parser, TokenMatcher, dialects } from "@cucumber/gherkin";

import { messages, IdGenerator } from "@cucumber/messages";

type PrettifyOptions =
  | { spaces: number; trailingNewLine: boolean }
  | { tabs: true; trailingNewLine: boolean };

function findIndex<T>(collection: T[], fn: (val: T) => boolean): number {
  for (let i = 0; i < collection.length; i++) {
    if (fn(collection[i])) {
      return i;
    }
  }

  return -1;
}

function isNumeric(content: string) {
  return !isNaN(parseFloat(content));
}

function minIndent(content: string) {
  const match = content.match(/^[ \t]*(?=\S)/gm);

  if (!match) {
    return 0;
  }

  return match.reduce((r, a) => Math.min(r, a.length), Infinity);
}

function stripIndent(content: string) {
  const indent = minIndent(content);

  if (indent === 0) {
    return content;
  }

  const regex = new RegExp(`^[ \\t]{${indent}}`, "gm");

  return content.replace(regex, "");
}

class State {
  private indent: number = 0;

  private pushed: {
    sourceLine: number;
    indent: number;
    content: string;
  }[] = [];

  constructor(private options: PrettifyOptions) {}

  withIncreasedIndent(fn: () => void) {
    this.indent++;
    fn();
    this.indent--;
  }

  push(content: string, sourceLine: number) {
    this.pushed.push({ content, sourceLine, indent: this.indent });
  }

  injectComment(content: string, sourceLine: number) {
    const insertAtIndex = findIndex(
      this.pushed,
      (line) => line.sourceLine > sourceLine
    );

    if (insertAtIndex === -1) {
      this.pushed.push({
        content,
        sourceLine,
        indent: 0,
      });
    } else {
      const indentOfCommentedLine = this.pushed[insertAtIndex]?.indent ?? 0;

      this.pushed.splice(insertAtIndex, 0, {
        content,
        sourceLine,
        indent: indentOfCommentedLine,
      });
    }
  }

  build() {
    if (this.pushed.length === 0) {
      return "";
    }

    const indent = (line: { content: string; indent: number }) => {
      if ("spaces" in this.options) {
        return " ".repeat(this.options.spaces * line.indent) + line.content;
      } else {
        return "\t".repeat(line.indent) + line.content;
      }
    };

    const lines: string[] = [];

    for (let i = 0; i < this.pushed.length; i++) {
      if (this.pushed[i].content === "") {
        lines.push("");
      } else {
        lines.push(indent(this.pushed[i]));
      }

      if (i !== this.pushed.length - 1) {
        const nextSourceLine = this.pushed[i + 1].sourceLine;

        if (this.pushed[i].sourceLine + 1 < nextSourceLine) {
          lines.push("");
        }
      }
    }

    if (this.options.trailingNewLine) {
      lines.push("");
    }

    return lines.join("\n");
  }
}

export function prettify(source: string, options: PrettifyOptions) {
  const document = new Parser(
    new AstBuilder(IdGenerator.uuid()),
    new TokenMatcher()
  ).parse(source);

  const state = new State(options);

  visitDocument(state, document);

  if (document.comments) {
    for (const comment of document.comments) {
      state.injectComment(comment.text!.trimStart(), comment.location!.line!);
    }
  }

  return state.build();
}

function visitDocument(state: State, document: messages.IGherkinDocument) {
  if (document.feature) {
    visitFeature(state, document.feature);
  }
}

function pushTitle(
  state: State,
  element:
    | messages.GherkinDocument.IFeature
    | messages.GherkinDocument.Feature.FeatureChild.IRule
    | messages.GherkinDocument.Feature.IScenario
    | messages.GherkinDocument.Feature.IBackground
    | messages.GherkinDocument.Feature.Scenario.IExamples
) {
  if (element.name) {
    state.push(
      element.keyword! + ": " + element.name!,
      element.location!.line!
    );
  } else {
    state.push(element.keyword! + ":", element.location!.line!);
  }
}

function visitFeature(
  state: State,
  feature: messages.GherkinDocument.IFeature
) {
  feature.tags?.map((tag) => visitTag(state, tag));

  pushTitle(state, feature);

  state.withIncreasedIndent(() => {
    if (feature.description) {
      const description = stripIndent(feature.description);

      const lines = description.split("\n");

      for (let i = 0; i < lines.length; i++) {
        state.push(lines[i], feature.location!.line! + i + 1);
      }
    }

    if (feature.children) {
      for (const child of feature.children) {
        visitChild(state, child);
      }
    }
  });
}

function visitChild(
  state: State,
  child: messages.GherkinDocument.Feature.IFeatureChild
) {
  if (child.rule) {
    visitRule(state, child.rule);
  } else if (child.background) {
    visitBackground(state, child.background);
  } else if (child.scenario) {
    visitScenario(state, child.scenario);
  }
}

function visitRule(
  state: State,
  rule: messages.GherkinDocument.Feature.FeatureChild.IRule
) {
  rule.tags?.map((tag) => visitTag(state, tag));

  pushTitle(state, rule);

  state.withIncreasedIndent(() => {
    if (rule.description) {
      const description = stripIndent(rule.description);

      const lines = description.split("\n");

      for (let i = 0; i < lines.length; i++) {
        state.push(lines[i], rule.location!.line! + i + 1);
      }
    }

    if (rule.children) {
      for (const child of rule.children) {
        visitChild(state, child);
      }
    }
  });
}

function visitBackground(
  state: State,
  background: messages.GherkinDocument.Feature.IBackground
) {
  pushTitle(state, background);

  state.withIncreasedIndent(() => {
    if (background.description) {
      const description = stripIndent(background.description);

      const lines = description.split("\n");

      for (let i = 0; i < lines.length; i++) {
        state.push(lines[i], background.location!.line! + i + 1);
      }
    }

    if (background.steps) {
      for (const step of background.steps) {
        visitStep(state, step);
      }
    }
  });
}

function visitScenario(
  state: State,
  scenario: messages.GherkinDocument.Feature.IScenario
) {
  scenario.tags?.map((tag) => visitTag(state, tag));

  pushTitle(state, scenario);

  state.withIncreasedIndent(() => {
    if (scenario.description) {
      const description = stripIndent(scenario.description);

      const lines = description.split("\n");

      for (let i = 0; i < lines.length; i++) {
        state.push(lines[i], scenario.location!.line! + i + 1);
      }
    }

    if (scenario.steps) {
      for (const step of scenario.steps) {
        visitStep(state, step);
      }
    }

    if (scenario.examples) {
      for (const example of scenario.examples) {
        visitExamples(state, example);
      }
    }
  });
}

function visitStep(state: State, step: messages.GherkinDocument.Feature.IStep) {
  state.push(step.keyword! + step.text!, step.location!.line!);

  state.withIncreasedIndent(() => {
    if (step.dataTable) {
      visitRows(state, step.dataTable.rows!);
    } else if (step.docString) {
      state.push(
        step.docString.delimiter! + step.docString.mediaType,
        step.docString.location!.line!
      );

      let docStringContent = step.docString.content!;

      if (step.docString.delimiter! === '"""') {
        docStringContent = docStringContent.replace(/"""/gm, '\\"\\"\\"');
      } else {
        docStringContent = docStringContent.replace(/```/gm, "\\`\\`\\`");
      }

      const lines = docStringContent.split("\n");

      for (let i = 0; i < lines.length; i++) {
        state.push(lines[i], step.docString.location!.line! + i + 1);
      }

      state.push(
        step.docString.delimiter!,
        step.docString.location!.line! + lines.length + 1
      );
    }
  });
}

function visitTag(
  state: State,
  tag: messages.GherkinDocument.Feature.ITag
): any {
  state.push(tag.name!, tag.location!.line!);
}

function visitExamples(
  state: State,
  example: messages.GherkinDocument.Feature.Scenario.IExamples
) {
  example.tags?.map((tag) => visitTag(state, tag));

  pushTitle(state, example);

  state.withIncreasedIndent(() => {
    visitRows(state, [example.tableHeader!, ...example.tableBody!]);
  });
}

function visitRows(
  state: State,
  rows: messages.GherkinDocument.Feature.ITableRow[]
) {
  const columnMaxWidths: number[] = [];

  for (let iRow = 0; iRow < rows.length; iRow++) {
    for (let iCell = 0; iCell < rows[iRow].cells!.length; iCell++) {
      columnMaxWidths[iCell] = Math.max(
        columnMaxWidths[iCell] ?? 0,
        rows[iRow].cells![iCell].value!.length
      );
    }
  }

  for (let iRow = 0; iRow < rows.length; iRow++) {
    const paddedValues = rows[iRow].cells!.map((cell, iCell) => {
      if (isNumeric(cell.value!)) {
        return cell.value!.padStart(columnMaxWidths[iCell], " ");
      } else {
        return cell.value!.padEnd(columnMaxWidths[iCell], " ");
      }
    });

    state.push(
      "| " + paddedValues.join(" | ") + " |",
      rows[iRow].location!.line!
    );
  }
}
```

**Comment by aslakhellesoy** [comment]
@badeball thanks for contributing this and sorry for not reviewibg this yet. I hope I’ll find some time to move this along in November.

**Comment by mattwynne** [comment]
This PR needs to be re-applied to the new repo at https://github.com/cucumber/gherkin-utils

**Comment by aslakhellesoy** [comment]
Thanks for the heads up, and for moving this out of the monorepo!

**Pull request closed without merging**
