### PR TITLE
gherkin: Extract from Monorepo

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary

The gherkin submodule has been extracted into its own repository at:

https://github.com/cucumber/gherkin

### CODE REVIEW

**Comment by mpkorstanje** [comment]
@davidjgoss the build is failing on what I guess are CJS vs ESM module problems. I've got no idea how to fix those. Could you help out with that?

**Comment by davidjgoss** [comment]
I’ll take a look.

**Comment by davidjgoss** [comment]
The error is because the `package-lock.json` has been deleted from the root of the repo - probably by accident?

To fix I think you need to restore that file and then run `npm i` from the root to have it updated.

**Comment by davidjgoss** [comment]
Okay, different failures now - I'll check this out this evening and have a play.

**Comment by davidjgoss** [comment]
Okay fixed the npm stuff, just need to update make and CI config accordingly.

**Comment by davidjgoss** [comment]
@mpkorstanje 🟢

**Review by davidjgoss — APPROVED** [review]

**Pull request merged**
