### PR TITLE
Fix docker-run make target to make it work with cucumber-build:0.10.0

### PR DESCRIPTION
**Pull request by aurelien-reeves**
## Summary

Update the docker-run make target to remove the former "cukebot" user from the command

## Details

With cucumber build image v0.10.0, the 'cukebot' user has been removed. The make targets have to be updated to consider that change

## Motivation and Context

The 'docker-run' make target did not work properly anymore

## How Has This Been Tested?

This is tested locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
One issue remain with NPM
It can actually not be installed globally with the root user.

Refs. https://stackoverflow.com/questions/51923277/npm-install-permission-denied-error-using-root-user

**Comment by aurelien-reeves** [comment]
Well, I have the same issue with the new cucumber-build v0.11.0 image which bring nvm.

```console
root@7325175f3ca3:/app# npm ci
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! code 127
npm ERR! path /app/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! sh: 1: node: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-28T16_20_57_238Z-debug-0.log
root@7325175f3ca3:/app# which npm
/root/.nvm/versions/node/v14.18.2/bin/npm
```

I would not spent too much time on this as it should not be an issue anymore soon once the monorepo will be split

**Comment by mattwynne** [comment]
the npm stuff works fine on my machine @aurelien-reeves. I ran `git clean -fdx` then `npm ci` then `make` and it all worked. I wonder what could be different about our environments? Maybe try the `git clean -fdx`?

**Comment by aurelien-reeves** [comment]
> the npm stuff works fine on my machine @aurelien-reeves. I ran `git clean -fdx` then `npm ci` then `make` and it all worked. I wonder what could be different about our environments? Maybe try the `git clean -fdx`?

Thansk for the tips
I gave it a try. Still the same issue.

The CI being green, the issue is certainly on my side actually 😓

**Comment by aurelien-reeves** [comment]
No more relevant as 0.12.0 bring cukebot user back

**Pull request closed without merging**
