### PR TITLE
Update Gherkin to use Messages DTOs instead of plain ruby hashes

### PR DESCRIPTION
**Pull request by aurelien-reeves**
Requires https://github.com/cucumber/common/pull/1601 to be merged first
Refs. https://github.com/cucumber/common/issues/1559

### CODE REVIEW

**Comment by luke-hill** [comment]
@aurelien-reeves after merging this, can we cut a new version of gherkin so I can then get my PR updated in the regular cucumber-ruby

**Comment by aurelien-reeves** [comment]
> 
> 
> @aurelien-reeves after merging this, can we cut a new version of gherkin so I can then get my PR updated in the regular cucumber-ruby

That's the plan
But it is not finished yet.

We have to write a json serializer for those DTOs
And to check the compatibility of all the modules with those new messages and gherkin.

But it is going well at the moment :)

**Comment by aslakhellesoy** [comment]
Isn't `JSON.stringify(envelope)` enough?

**Comment by aurelien-reeves** [comment]
> 
> 
> Isn't `JSON.stringify(envelope)` enough?

This is not javascript, this is ruby

**Comment by aurelien-reeves** [comment]
Once https://github.com/cucumber/common/pull/1605 is merged, I'll be able to continue on this one. Hopefully there won't be too much to do to make it pass.

**Comment by aurelien-reeves** [comment]
If no objection soon, I'll force-merge it to be able to start releasing new versions of some modules in the mono-repo

If any objection, I'll wait for proper reviews :)

**Review by aslakhellesoy — APPROVED** [review]
LGTM!

**Pull request merged**
