### PR TITLE
Use multi-arch build container

### PR DESCRIPTION
**Pull request by mattwynne**
Using this PR to lean on our CI to test the new multi-arch container for our build environment.

See https://github.com/cucumber/cucumber-build/pull/12

### CODE REVIEW

**Comment by mattwynne** [comment]
OK, so as we'd expect, this is failing without mono

**Comment by aslakhellesoy** [comment]
This is passing now. We only run `mono` if the parser needs to be regenerated, but since it's committed to `git`, that's never necessary in CI. It is however needed for local development (in docker) whenever we change the Gherkin grammar.

So we need to manually check that we can regenerate the parser locally after a modification to `gherkin.razor`.

**Comment by mattwynne** [comment]
@gasparnagy's take is that we only needed the `mono-runtime` package, not `mono-devel` which seems to have installed find on both architectures, so I think we have a good image now.

**Comment by mattwynne** [comment]
Grrr, dunno why CircleCI won't start this container. I'll try pushing an image with a unique tag.

**Comment by mattwynne** [comment]
I have no idea why CircleCI is failing the build now. It says

```
CircleCI was unable to run the job runner because we were unable to execute commands in build container.

This typically means that the build container entrypoint or command is terminating the container prematurely, or interfering with executed commands.  Consider clearing entrypoint/command values and try again.
```

Nothing has changed about the container image that affects the entrypoint, and I can enter it via `make docker-run` and run commands in it fine on my local machine.

Anyone got ideas how to get past this?

**Comment by aslakhellesoy** [comment]
Can you remove the formatting edits please?

**Comment by mattwynne** [comment]
@aslakhellesoy done. I'm still none the wiser what's up with CircleCI here

**Comment by aslakhellesoy** [comment]
Dunno - I can try to have a look tomorrow or next week

**Comment by mattwynne** [comment]
I'm scared to merge this in until we figure it out. I've asked CircleCI support about it.

**Comment by aslakhellesoy** [comment]
It’s obviousy not mergable :-)

**Comment by mattwynne** [comment]
I had accidentally pushed a tag that only had an `arm64` arch image. It's looking better now.

**Comment by aslakhellesoy** [comment]
Great work @mattwynne! What's left to do? Release 0.4.0 of the image and use that?

**Comment by mattwynne** [comment]
Yep! I'll merge https://github.com/cucumber/cucumber-build/pull/12 and make a 0.4.0 release. There are a couple more issues to work through but I think we're off the build platform and into the code now.

**Comment by mattwynne** [comment]
@gasparnagy @aslakhellesoy any idea why the series build failed but the parallel one didn't? It looks like the problem in the series build was in building gherkin/go, and Berp couldn't find .NET:

```
if [[ -d go ]]; then cd go && make default; fi
make[2]: Entering directory '/home/cukebot/cucumber/gherkin/go'
mono  /var/lib/berp/1.1.1/tools/net471/Berp.exe -g gherkin.berp -t parser.go.razor -o parser.go
Berp 1.1.1
Copyright (C) 2014-2020, Gaspar Nagy (Spec Solutions)
Licensed under the Apache License, Version 2.0 (the "License")
    http://www.apache.org/licenses/LICENSE-2.0

Generating parser for grammar 'gherkin.berp' using template 'parser.go.razor'.
Loading grammar...
The grammar was loaded with 14 tokens and 19 rules.
Calculating parser states...
51 states calculated for the parser.
Generating parser class...

Generation failed.
Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
make[2]: *** [Makefile:94: parser.go] Error 1
make[2]: Leaving directory '/home/cukebot/cucumber/gherkin/go'
make[1]: *** [default.mk:17: default-go] Error 2
make[1]: Leaving directory '/home/cukebot/cucumber/gherkin'
make: *** [Makefile:26: default-gherkin] Error 2

Exited with code exit status 2
```

**Comment by aslakhellesoy** [comment]
I'm not sure why it failed.

What's more puzzling to me is why it ran in the first place. The generated `parser.go` is added to git, and unless its Makefile dependencies (`gherkin.berp` or `parser.go.razor`) have more recent timestamps, it shouldn't have to be regenerated.

Berp typically only needs to run on developer workstations when the grammar or template is modified.

**Pull request merged**
