### PR TITLE
gherkin (Python): Updating to Python 3 (standard minimum supported version is now 3.7)

### PR DESCRIPTION
**Pull request by jsa34**
…but technically the code supports Python 3.3+)

## Summary

A general code clean up to remove references to Python2 and any other unsupported versions.  Technically the code supports Python 3.3+, but unintentionally.

## Motivation and Context

Prepare for feature changes without having to support unnecessary backwards-compatability

## How Has This Been Tested?

Unit tests run as expected

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by jsa34** [comment]
Apologies - I accidentally made a branch against the cucumber project itself, rather than a fork!  (Slap on the wrist and will do so going forward!)

**Comment by jsa34** [comment]
Build fails after merging "main" into this branch - not sure about the cause:

Working copy is dirty. Please run 'source scripts/functions.sh && rsync_files' and commit modified files.
Found: 
 M gherkin/python/default.mk
make: *** [Makefile:34: check_synced] Error 1

**Comment by jsa34** [comment]
Thank you so much for your assistance, @aurelien-reeves !  The build seems happy again :)

**Comment by aurelien-reeves** [comment]
So, the big question here is: do everyone agree to end support for python 2?

@aslakhellesoy @jenisys?

Myself, I would agree. But I am not really a python developer so I may miss some background here

**Comment by jsa34** [comment]
I am just fixing the parser.py being generated from the razor file (An oversight!)  Just in case anyone accidentally merges.

I managed to get the WSL setup you recommended working - I had problems with gitbash on Windows, but WSL works a treat!  Thanks for your time once again, Aurelien!
________________________________

**Comment by jsa34** [comment]
Resolved the issue with using the Razor file to generate parser.py.

**Pull request closed without merging**
