### PR TITLE
Move progress formatter to the mono-repo

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

The formatter should all be in the mono-repo to ensure consistency of behaviour between the different implementations of Cucumber.
Also they should consume messages. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [x] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
I'm thinking that having a library per formatter may not be such a good idea. What would you think to have instead a `cucumber/console-formatters` library that would handle formats the following format ?
 - `progress`
 - `pretty`
 - `summary` 

Maybe the `usage` formatter could all belong there.

**Comment by mpkorstanje** [comment]
> I'm thinking that having a library per formatter may not be such a good idea.

Why not?

**Comment by vincent-psarga** [comment]
> Why not?

The different terminal formatter (progress, pretty and summary) hare lot of common code (handling ANSI colors, printing the summary at the bottom).
It would be simpler to handle releases of a single `console-formatter` than of 3 or 4 different libraries.

**Comment by mpkorstanje** [comment]
Sounds good to me.

**Comment by mattwynne** [comment]
@vincent-psarga do you have any recollection of what's left to do on this?

**Comment by vincent-psarga** [comment]
> @vincent-psarga do you have any recollection of what's left to do on this?

I'd say more or less everything :D
 - port to other languages
 - add tests based on messages to ensure every language behaves the same way

But the main issue here was that the progress formatter relies heavily on common code with other formatters, so as I mentioned earlier, having simply a "progress-formatter" library might not be such a good idea.

**Comment by mattwynne** [comment]
I think it would be fine to start by moving just cucumber-ruby's progress formatter into a separate gem in the common repo, and we could gradually migrate other formatters and languages in other PRs, once we've figured out a good way to make a shared test suite.

No need to try and boil the ocean; that's how things get stuck 😁

**Comment by vincent-psarga** [comment]
> No need to try and boil the ocean; that's how things get stuck 😁

Indeed :)

**Comment by aurelien-reeves** [comment]
Well, we are actually splitting the mono-repo now. We did not felt that happy with it. So, closing this PR

However we could still have a polyglot repo for formatters like the progress formatter

**Pull request closed without merging**
