### PR TITLE
Messages: codegen for ruby DTOs

### LINKED ISSUE #1574: Generate Ruby DTOs for messages
## Summary

We're currently using a plain old Ruby Hash to represent message payloads. It will be simpler for consumers if we can de-serialize the messages into simple Ruby value objects, (or DTO - Data Transfer Objects) and pass those around instead.

## Expected Behavior

API consumers should receive messages as Ruby objects instead of hashes.

## Possible Solution

See Aslak's advice [here](https://github.com/cucumber/cucumber-ruby/pull/1544#issuecomment-847734909).

### PR DESCRIPTION
**Pull request by aurelien-reeves**
## Summary

Add a code generator for messages to generate ruby DTOs instead of relying on plain ruby hashes

Refs. #1574 #1559

## Details

Add templates and class to Codegen for ruby DTOs

## Motivation and Context

Cf. #1574

## How Has This Been Tested?

N/A

## Types of changes

- New feature (non-breaking change which adds functionality).

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Before going further - like using those DTOs in cucumber-gherkin - I suggest to review and merge that PR as-is while it is still relatively small and easy to review.

Then we could open a new PR dedicated to using those DTOs into Gherkin.

WDYT?

**Comment by mattwynne** [comment]
I think this is for a separate PR, but the idea occurs to me that we could include some small amount of RDoc in the generated code, perhaps just referencing some other place where we document the message protocol.

**Comment by aslakhellesoy** [comment]
Might as well put that in now I think. The URL to the documentation is https://github.com/cucumber/common/tree/main/messages#readme

**Review by mattwynne — APPROVED** [review]

**Comment by aurelien-reeves** [comment]
Great idea!

I have even added the documentation that is already in the json schemas into the generated DTOs.

We may do that for typescript and go.

Some formatting is part of the schemas. We may also clean those a little bit.

But that can be done in other PR, I will merge this one soon to move on the ruby DTOs: using those within gherkin.

**Pull request merged**
