### PR TITLE
Convert ruby messages duration.nanos to integer

### PR DESCRIPTION
**Pull request by aurelien-reeves**
`duration.nanos` is described in the schema as being an integer. It was already the case with protobuf.

With the new DTOs, `duration.nanos` became a float. When using the json-formatter to convert ndjson to "legacy" json, an error is raised:

```
ERROR: json: cannot unmarshal number 127100.0 into Go struct field Duration.testStepFinished.testStepResult.duration.nanos of type int64
```

Converting nanos to integer should fix this.

## How Has This Been Tested?

As durations are removed when validating messages as part of the neutralize-json scripts, this is not properly tested yet in the mono-repo.
I encounter this issue while trying to reactivate the CCK tests with cucumber-ruby. So there will be at least that way to test it.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue).

## Checklist:

- [x] I've added tests for my code.
- [x] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
I think we should also patch json-formatter to handle floats, so it works with those ruby versions that output a float.

**Comment by aurelien-reeves** [comment]
> I think we should also patch json-formatter to handle floats, so it works with those ruby versions that output a float.

For now no ruby version output float at the moment.
However I check how difficult that would be

**Comment by aurelien-reeves** [comment]
From some tests I did on cucumber-ruby main branch but not released yet

**Comment by aurelien-reeves** [comment]
> 
> 
> I think we should also patch json-formatter to handle floats, so it works with those ruby versions that output a float.

Due to the strong type system of Golang, that may be doable but it looks pretty difficult.
As the issue has not been released yet, would it be ok to merge and release this PR quickly in order to avoid releasing this known bug with cucumber-ruby? That way, we would not have to patch json-formatter

**Pull request merged**
