### PR TITLE
gherkin-languages: add US-Texan localisation

### PR DESCRIPTION
**Pull request by willmac321**
Add an en-tx (US Texan) localisation :)  Thank's y'all!

## Summary
Add a US Texan localization to gherkin-languages.json

## Motivation and Context

Regarding the question about solving, it makes it so I can understand y'all better!  Also for the memes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Lovely! Did you know we used to have a Texan translation at some point contributed by an idiot?

https://github.com/cucumber-attic/gherkin2/commit/0e9322ae9e71c54590b062e4bedc812fd4c3b58c

**Comment by willmac321** [comment]
Hahaha that is too funny!  I had a chuckle seeing that one!

**Comment by mattwynne** [comment]
I need to see a full example of a scenario using this language! 😀

**Comment by willmac321** [comment]
> I need to see a full example of a scenario using this language! 😀

Haha, I'll try to get this for y'all!  I need to run through y'all's checklist still.  :D

**Comment by aslakhellesoy** [comment]
Hi @willmac321,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
