### PR TITLE
PHP Gherkin Parser: v24 is not compatible with v18 of messages

### PR DESCRIPTION
**Pull request by dantleech**
## Summary

Updated `composer.json` to require at least v19 of cubumber PHP messages

## Details

When using v24 with lowest dependencies:

```
cucumber/gherkin                      v24.0.0     Gherkin parser
cucumber/messages                     v18.0.0     JSON schema-based messages for Cucumber's inter-process communication
```

We get the following error:

```
PHP Fatal error:  Uncaught Error: Class "Cucumber\Messages\Step\KeywordType" not found in /home/daniel/www/dantleech/gherkin-lint/vendor/cucumber/gherkin/src/GherkinParser.php:38
```

With v19.0.0 of cucumber/messages it works.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

### CODE REVIEW

**Comment by dantleech** [comment]
cc @ciaranmcnulty

**Comment by ciaranmcnulty** [comment]
Thanks @dantleech that's annoying

What would be the best away to detect this? `composer install --prefer-lowest`?

**Comment by dantleech** [comment]
yes, that's what I'm doing with [GH actions](https://github.com/dantleech/gherkin-lint-php/blob/master/.github/workflows/ci.yml#L72)

**Comment by aurelien-reeves** [comment]
Thanks @dantleech for the patch 👍
@ciaranmcnulty is it fine? Can we merge?

**Review by aurelien-reeves — DISMISSED** [review]
An entry in the changelog is missing actually ☺️

**Comment by aurelien-reeves** [comment]
Do we try to add a non-regression test as part of this PR? Or do we quickly release the patch asap and work on a new test in another PR?

**Comment by ciaranmcnulty** [comment]
I think it should be merged with changelog entry

I am so confused by the Makefiles in this repo that I'm to sure how to add a second job effectively :/ It basically needs a second CI job that can run `composer update --prefer-lowest` either initially, or later on (to downgrade dependencies) before running tests

**Comment by ciaranmcnulty** [comment]
@aurelien-reeves we could defer until repo split puts it all in GHA ;)

**Comment by ciaranmcnulty** [comment]
@aurelien-reeves actually by explaining it I realised maybe it's easy #2035

**Comment by ciaranmcnulty** [comment]
Before merging this I'd like to have a small stab at making it backwardly compatible

**Comment by ciaranmcnulty** [comment]
Oh wait the testdata has the new fields in, no chance :)

**Comment by aurelien-reeves** [comment]
> Before merging this I'd like to have a small stab at making it backwardly compatible

I would have been pleased to find some ways to make it backward compatible indeed.
But as long as this has already been released, I think it is too late.

Having distinct repos in a near future will certainly help improving backward compatibility when working on new features like we did

**Comment by aslakhellesoy** [comment]
Hi @dantleech,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
