### PR TITLE
Add further examples for valid Cucumber files to pretty-print

### PR DESCRIPTION
**Pull request by jamietanna**
## Summary

Following up on the changes for cucumber/gherkin-utils#4, via cucumber/common#1725 and cucumber/common#1985, we're still missing some key areas of improvement for pretty-printing, in which I'd be hesitant to recommend folks use this until they're resolved - or at least we better document what "expected" behaviour is.

## Motivation and Context

See above summary.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by jamietanna** [comment]
CC @nddipiazza @aslakhellesoy

**Comment by jamietanna** [comment]
Just raising this for visibility, be great if either of you fancies picking this up :pray:

**Comment by mattwynne** [comment]
@jamietanna thanks for this contribution! We're migrating the code for gherkin-utils into a separate repo (https://github.com/cucumber/gherkin-utils)

Would you mind making this same PR against that repo? I don't think I have the power to transfer it for you unfortunately.

**Comment by blacelle** [comment]
@jamietanna Should this be moved into gherkin-utils ? As this will be integrated into Spotless, some additional users would encounter these limitations.

**Comment by jamietanna** [comment]
Yes, feel free to - I'm unfortunately not going to be able to get round to this - happy to share some more examples from my library that may be of interest, where there's a few more of the complex examples that we should handle

**Comment by blacelle** [comment]
Dine in https://github.com/cucumber/gherkin-utils/pull/20

I may have a look if you have other specific broken cases.

**Pull request closed without merging**
