### PR TITLE
Use native RegExp Match indices

### PR DESCRIPTION
**Pull request by aslakhellesoy**
## Summary

Use [RegExpExecArray#indices](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) to get the position of capture groups.

## Details

This PR removes the dependency on the [becke-ch--regex--s0-0-v1--base--pl--lib](https://www.npmjs.com/package/becke-ch--regex--s0-0-v1--base--pl--lib) library and uses `RegExpExecArray#indices` instead.

[RegExp Match Indices](https://github.com/tc39/proposal-regexp-match-indices) were introduced in v8 v9.0.259. The first Node.js release to use a v8 newer than that is [16.4.0](https://nodejs.org/en/download/releases/).

Since we cannot drop support for Node.js < 16.4.0 until 2023/2024, the implementation currently uses a [polyfill](https://github.com/rbuckton/regexp-match-indices).

## Motivation and Context

The main motivation for this change is to stop depending on http://www--s0-v1.becke.ch/tool/becke-ch--regex--s0-v1/becke-ch--regex--s0-0-v1--homepage--pl--client/, which seems to be a liability to depend on because it doesn't seem to have a public Git repo, except for [this fork](https://github.com/TheWorldTable/regexp-plus).

I would also expect this to be slightly more performant since it's based on a native implementation, but I doubt it will be significant for end users.

Also see https://github.com/cucumber/common/issues/300

## How Has This Been Tested?

The tests pass on Node v16.4.2, but I doubt it will pass on Node < 16.4.0 as explained above.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [x] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Update: I added the polyfill so we don't have to wait until 2023/2024 to merge this.

**Review by aurelien-reeves — APPROVED** [review]
👍

**Comment by mattwynne** [comment]
👍 

If we're using the polyfill let's edit the text in the PR to reflect that and remove the warnings.

**Comment by aslakhellesoy** [comment]
PR text updated

**Pull request merged**
