### PR TITLE
tag-expressions: Remove deprecated method use_2to3

### LINKED ISSUE #1736: cucumber-tag-expressions install failing on newer versions of setuptools
**Describe the bug**
I'm starting to see pip install failures in Github Actions due to the use of `use_2to3` in cucumber-tag-expressions. Setuptools deprecated use of `use_2to3` from v58 (see [changelog](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0)).

So an alternative approach will be needed, or dropping support for Python 2. Figured this is a call for the maintainers hence an issue rather than a PR.

Thanks for a great package though :)

**To Reproduce**
```
pip install setuptools>=58.0.0
pip install cucumber-tag-expressions
```
See error:
```
Collecting cucumber-tag-expressions
  Downloading cucumber-tag-expressions-4.0.0.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/gez/git/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8upi3hmn/cucumber-tag-expressions/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8upi3hmn/cucumber-tag-expressions/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8upi3hmn/cucumber-tag-expressions/pip-egg-info
         cwd: /tmp/pip-install-8upi3hmn/cucumber-tag-expressions/
    Complete output (3 lines):
    /home/gez/git/.venv/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
      warnings.warn(
    error in cucumber-tag-expressions setup command: use_2to3 is invalid.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
Should successfully install using newer versions of setuptools.

**Context & Motivation**
Discovered this as our Github Actions started failing - hence we need to actively downgrade setuptools in 3rd party CI systems or fork the cucumber package and remove use_2to3.

**Your Environment**
Replicated on
 - Ubuntu 21.04
 - Github Actions

### PR DESCRIPTION
**Pull request by krisgesling**
## Summary
Removes the call to `use_2to3` in setup.py as this method has been deprecated in setuptools>=58.0.0  (see [changelog](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0)).

Fixes #1736

## Details

The standard library module lib2to3 is deprecated and will be removed in Python 3.10.

Further details about why this was deprecated can be found here:
https://github.com/pypa/setuptools/issues/2086

## Motivation and Context

Installation of cucumber-tag-expressions will fail if the system is using newer versions of setuptools. This is actively occuring on Github Actions.

## How Has This Been Tested?
```
pip install setuptools>=58.0.0
pip install cucumber-tag-expressions
```
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).

I haven't tested on Python2 and am not familiar with the details of `use_2to3` so this may be a breaking change.

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by graingert** [comment]
You'll need to apply 2to3 to the source code and set a `python_requires >= '3.6'`

**Review by aurelien-reeves — APPROVED** [review]
Great, thank you!

**Review by graingert — CHANGES_REQUESTED** [review]
you'll need to apply lib2to3 to the source code for your package to support py3

**Comment by graingert** [comment]
you could alternatively use https://github.com/PyCQA/modernize to keep python2 support

**Comment by graingert** [comment]
actually it looks like 2to3 was redundant in this project:

```
diff --git a/tag-expressions/python/cucumber_tag_expressions/__init__.py b/tag-expressions/python/cucumber_tag_expressions/__init__.py
index 45b88a343..0877fdfc4 100644
--- a/tag-expressions/python/cucumber_tag_expressions/__init__.py
+++ b/tag-expressions/python/cucumber_tag_expressions/__init__.py
@@ -13,7 +13,7 @@ Theses selected items are normally included in a test run.
 .. _`behave: Gherkin`: https://behave.readthedocs.io/en/latest/philosophy.html#the-gherkin-language
 """
 
-from __future__ import absolute_import
+
 from .parser import parse, TagExpressionParser, TagExpressionError
 
 __version__ = "1.1.2"
diff --git a/tag-expressions/python/cucumber_tag_expressions/parser.py b/tag-expressions/python/cucumber_tag_expressions/parser.py
index 792c065ad..71aba994b 100644
--- a/tag-expressions/python/cucumber_tag_expressions/parser.py
+++ b/tag-expressions/python/cucumber_tag_expressions/parser.py
@@ -14,7 +14,7 @@ UNSUPPORTED:
 * Support special tags w/ escaped-parens: ``@reqid\\(10\\)``
 """
 
-from __future__ import absolute_import
+
 from enum import Enum
 from cucumber_tag_expressions.model import Literal, And, Or, Not, True_
 
@@ -154,7 +154,7 @@ class TagExpressionParser(object):
     """
     # pylint: disable=too-few-public-methods
     TOKEN_MAP = {token.keyword: token
-                 for token in Token.__members__.values()}
+                 for token in list(Token.__members__.values())}
 
     @classmethod
     def select_token(cls, text):

```

**Review by graingert — APPROVED** [review]

**Review by aurelien-reeves — APPROVED** [review]

**Comment by aurelien-reeves** [comment]
@krisgesling @graingert thanks a lot folks! 🤩

For the moment, we do not have much python contributors to the cucumber projects. So, thank you very much for your contribution!

If you still have the possibility to submit other contribution, feel free to do so 😅

We have a dedicated slack workspace. Again, feel free to join! You can [register](https://cucumberbdd-slack-invite.herokuapp.com/) then head over to [#intro](https://cucumberbdd.slack.com/messages/C5WD8SA21/).

Finally, note that there is an [Open Collective for Cucumber](https://opencollective.com/cucumber). You can be pay for your contributions!

**Comment by aslakhellesoy** [comment]
Hi @krisgesling,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by krisgesling** [comment]
Thanks @aslakhellesoy - this is a great welcome message for new contributors!

I very much appreciate the great package you and the team have built too.

**Pull request merged**
