### PR TITLE
Update CoC with the new location

### PR DESCRIPTION
**Pull request by mattwynne**
Updated scope and other details as per Rien's suggestions in #2194.

We still need to decide who else (other than me( wants to be a moderator.

I've removed everyone else for now, I figure people can put up their hands to be added back in.

@cucumber/committers please update this PR adding your name if you'd like to be on the list of moderators.

### CODE REVIEW

**Comment by bv** [comment]
🖐🏻 putting up my hand to be added as moderator, new one, as I have never been one

**Comment by mpkorstanje** [comment]
@mattwynne it also look like the code of conduct got duplicated. I think it would be better to delete the one from `common` and use the one from `.github`.

https://github.com/cucumber/.github/blob/main/CODE_OF_CONDUCT.md

**Comment by mattwynne** [comment]
Well spotted @mpkorstanje.

I've moved the commits here over to [a PR on that repo](https://github.com/cucumber/.github/pull/52).

There's a vanity URL (https://cucumber.io/conduct) which redirects to the file on this repo, and since we're unable to change that redirect until we get control over the domain again, I've updated the file to just be a signpost to the file on the `.github` repo.

Make sense?

**Comment by mpkorstanje** [comment]
Works for me! 👍

**Review by davidjgoss — APPROVED** [review]

**Comment by Johnlon** [comment]
i could.help with moderation

**Comment by mattwynne** [comment]
Thanks @Johnlon. Please update the PR on https://github.com/cucumber/.github/pull/52 with your details and send us a quick email.

**Pull request merged**
