### PR TITLE
Set the inlineSources tsconfig setting to true

### LINKED ISSUE #2039: Source code not included in sourcemaps
### 👓 What did you see?

Using `@cucumber/messages` raises warnings during compilation:
```terminal
WARNING in ../../node_modules/@cucumber/messages/dist/esm/src/version.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '~/project/node_modules/@cucumber/messages/src/version.ts' file: Error: ENOENT: no such file or directory, open '~/project/node_modules/@cucumber/messages/src/version.ts'
 @ ../../node_modules/@cucumber/messages/dist/esm/src/index.js 5:0-39 7:0-87
 @ ../tests/features/scenarios.ts 4:0-47 26:54-108
 @ ./src/scenarios.ts 4:0-86 8:4-16
 @ ./src/App.tsx 9:0-61 53:43-52 53:53-75 62:94-103 62:106-115
 @ ./src/index.tsx 8:0-24 13:35-38
```

### ✅ What did you expect to see?

The source code to be included in the source maps.

### 📦 Which tool/library version are you using?

- `"@cucumber/messages": "^18.0.0"`

### 🔬 How could we reproduce it?

1. install any frontend framework (e.g. [CRA](https://create-react-app.dev/))
2. add the dependency
3. import `@cucumber/messages` and use it (e.g. with `generateMessages` from `@cucumber/gherkin`)

In my case I'm using it like this:
```ts
const [{ gherkinDocument }] = generateMessages(
  source,
  'happy_path.feature',
  messages.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN,
  {
    includeGherkinDocument: true,
    includePickles: false,
    includeSource: false,
    newId: () => Math.random().toString(),
  },
)
```

### 📚 Any additional context?

This could be fixed in one of two ways:
1. publish the `src` folder in all the projects (e.g. add it to https://github.com/cucumber/messages-javascript/blob/main/package.json#L9)
2. set [inlineSources](https://www.typescriptlang.org/tsconfig#inlineSources) to `true` in the base [`tsconfig.build.json`](https://github.com/cucumber/common/blob/main/tsconfig.build.json)

### PR DESCRIPTION
**Pull request by EnoahNetzach**
## Summary

This adds the `inlineSources` setting in `tsconfig` (see https://www.typescriptlang.org/tsconfig#inlineSources)

## Details

Fixes #2039.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [x] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by mattwynne** [comment]
@davidjgoss do you agree this is the right option vs the alternative suggested in #2039? I don't have enough context to have a strong opinion.

Should we be doing this across the board in our TypeScript codebases?

**Comment by davidjgoss** [comment]
@mattwynne yep this is the best way IMO. It’s what we do in cucumber-js. Only time I’d recommend externalised source maps would be doing a browser bundle.

**Review by davidjgoss — APPROVED** [review]

**Comment by mattwynne** [comment]
Thanks @EnoahNetzach!

**Comment by mattwynne** [comment]
@aurelien-reeves this will need to be ported to the new repo as part of #2029

**Comment by EnoahNetzach** [comment]
Thanks to you all!

**Pull request merged**
