### PR TITLE
Enable overriding components used in @cucumber/react

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

In order to ease integration of `@cucucmber/react` into other tools, we need to make sure than it is possible to override/customize the components used for rendering.
This PR proposes a solution allowing to override/change the Attachments` component, if proved useful, it may be applied to other components.

Also, I moved all the `Context` objects into a `/contexts` folder, similar to `/components` as we start having too much of them ;)

## Details

As we render everything based on the Gherkin AST, trying to pass properties to `GherkinDocumentList` will quickly become a mess.
The idea here is to have a new `Context` object, called `MessageToComponentMappingContext` which provides a mapping between a `message` and the component used to render it.

We will not make all components customisable for now, this PR focuses on the Attachments ad if it works fine, it will be generalised based on our need.

## Motivation and Context

Enable customisation of the components in other applications than `cucumber-html-report`

## How Has This Been Tested?

With some mocha tests ensuring we can override the component.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] The change has been ported to JavaScript.
- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Can you add a StoryBook example?

**Comment by vincent-psarga** [comment]
I've added an extra component to lookup which component to use, but I'm definitely not a fan of the name (`CustomizableAttachment`), if anyone has a better idea, I take it :)

> Can you add a StoryBook example?

Done :)

**Comment by aslakhellesoy** [comment]
I'd like to upgrade StoryBook as part of this PR. We're long overdue upgrading to v6.

I know there is an argument for doing that in a separate PR. However, separate issues for doing upgrades tend to be down-prioritised.

By having a policy that states "Every PR should also make sure all dependencies are the most recent ones", we're adding a bit of boy-scouting to our process....

**Comment by aslakhellesoy** [comment]
Bump

**Comment by aslakhellesoy** [comment]
This is superseded by https://github.com/cucumber/common/pull/1391

**Pull request closed without merging**
