### PR TITLE
Remove Gherkin DotNet implementation

### PR DESCRIPTION
**Pull request by ehuelsmann**
## Summary

On advice of @gasparnagy, because nobody uses it and it has
fallen out of date, being still based on protobuf.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [x] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by ehuelsmann** [comment]
> The CI is configured in `.circleci/config.yml` :)

Totally forgot about that! Thanks!

**Comment by aurelien-reeves** [comment]
Do we remove gherkin only? Or other dotnet thing like, at least, messages/dotnet?

**Comment by ehuelsmann** [comment]
@gasparnagy  did I understand correctly that you *do* want to use messages (especially after #1741), but not gherkin?

**Comment by gasparnagy** [comment]
I will try to attend the weekly meeting tomorrow and maybe it is easier to resolve the misunderstanding there.

**Comment by aurelien-reeves** [comment]
Oh, ok! Thanks for the info @gasparnagy
That was close!😅

**Comment by ehuelsmann** [comment]
Ok! Well then we want to close this PR for sure!

**Pull request closed without merging**
